version: "3.2"

services:
  fluentd:
    build: $PWD/fluentd
    container_name: EFK-fluentd
    user: root
    restart: unless-stopped
    volumes:
      - $PWD/fluentd/fluentd-conf:/fluentd/etc
      - certs:/fluentd/certs
    ports:
      - "24224:24224"

volumes:
  certs:
    driver: local
    name: es-certs

networks:
  default:
    driver: bridge
    name: efk-network
